# Generated by Django 3.2.25 on 2024-09-21 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone', models.CharField(max_length=20, null=True)),
                ('default_eircode', models.CharField(max_length=15, null=True)),
                ('default_country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('default_address1', models.CharField(max_length=50, null=True)),
                ('default_address2', models.CharField(max_length=50, null=True)),
                ('default_town_city', models.CharField(max_length=50, null=True)),
                ('default_county_region', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
