# Generated by Django 3.2.25 on 2024-09-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('body', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
