# Generated by Django 3.2.25 on 2024-10-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-post_date']},
        ),
    ]
