# Generated by Django 3.2.25 on 2024-10-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comment'),
        ('shopping_bag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('exclusive', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
